create table PASSENGERS
(
    PASSENGER_ID   VARCHAR2(20)  not null,
    USER_ID        VARCHAR2(255) not null,
    PASSENGER_NAME VARCHAR2(20)  not null,
    ID_NUMBER      VARCHAR2(255)
)
/

INSERT INTO SYSTEM.PASSENGERS (PASSENGER_ID, USER_ID, PASSENGER_NAME, ID_NUMBER) VALUES ('003', '12345', 'xjb', 'string');
INSERT INTO SYSTEM.PASSENGERS (PASSENGER_ID, USER_ID, PASSENGER_NAME, ID_NUMBER) VALUES ('12345', '111', 'zhc', '001');
INSERT INTO SYSTEM.PASSENGERS (PASSENGER_ID, USER_ID, PASSENGER_NAME, ID_NUMBER) VALUES ('111', '12345', 'ssj', '002');
INSERT INTO SYSTEM.PASSENGERS (PASSENGER_ID, USER_ID, PASSENGER_NAME, ID_NUMBER) VALUES ('8', '2', '牟泳祯', '123456789123456789');