create table ORDERLIST
(
    ORDER_ID     VARCHAR2(20) not null
        constraint PK_ORDER_ID
            primary key,
    USER_ID      VARCHAR2(20),
    TRAIN_ID     VARCHAR2(20),
    ORDER_STATUS VARCHAR2(20),
    PRICE        NUMBER,
    TICKET_TYPE  VARCHAR2(20),
    PASSENGER_ID VARCHAR2(20)
)
/

INSERT INTO SYSTEM.ORDERLIST (ORDER_ID, USER_ID, TRAIN_ID, ORDER_STATUS, PRICE, TICKET_TYPE, PASSENGER_ID) VALUES ('007', '2', '00001', 'unpaid', 100, 'adult', '1');
INSERT INTO SYSTEM.ORDERLIST (ORDER_ID, USER_ID, TRAIN_ID, ORDER_STATUS, PRICE, TICKET_TYPE, PASSENGER_ID) VALUES ('003', '1', '00001', 'paid', 100, 'adult', '2');
INSERT INTO SYSTEM.ORDERLIST (ORDER_ID, USER_ID, TRAIN_ID, ORDER_STATUS, PRICE, TICKET_TYPE, PASSENGER_ID) VALUES ('004', '1', '00002', 'paid', 100, 'student', '1');
INSERT INTO SYSTEM.ORDERLIST (ORDER_ID, USER_ID, TRAIN_ID, ORDER_STATUS, PRICE, TICKET_TYPE, PASSENGER_ID) VALUES ('005', '2', '00001', 'paid', 100, 'adult', '2');
INSERT INTO SYSTEM.ORDERLIST (ORDER_ID, USER_ID, TRAIN_ID, ORDER_STATUS, PRICE, TICKET_TYPE, PASSENGER_ID) VALUES ('002', '2', '00002', 'unpaid', 100, 'student', '2');
INSERT INTO SYSTEM.ORDERLIST (ORDER_ID, USER_ID, TRAIN_ID, ORDER_STATUS, PRICE, TICKET_TYPE, PASSENGER_ID) VALUES ('001', '2', '00001', 'unpaid', 100, 'student', '2');
INSERT INTO SYSTEM.ORDERLIST (ORDER_ID, USER_ID, TRAIN_ID, ORDER_STATUS, PRICE, TICKET_TYPE, PASSENGER_ID) VALUES ('008', '2', '00001', 'unpaid', 100, 'student', '1');
INSERT INTO SYSTEM.ORDERLIST (ORDER_ID, USER_ID, TRAIN_ID, ORDER_STATUS, PRICE, TICKET_TYPE, PASSENGER_ID) VALUES ('009', '2', '00001', 'unpaid', 200, 'student', '1');
INSERT INTO SYSTEM.ORDERLIST (ORDER_ID, USER_ID, TRAIN_ID, ORDER_STATUS, PRICE, TICKET_TYPE, PASSENGER_ID) VALUES ('010', '2', '00001', 'unpaid', 200, 'student', '2');
INSERT INTO SYSTEM.ORDERLIST (ORDER_ID, USER_ID, TRAIN_ID, ORDER_STATUS, PRICE, TICKET_TYPE, PASSENGER_ID) VALUES ('012', '2', '00001', 'paid', 200, 'adult', '2');
INSERT INTO SYSTEM.ORDERLIST (ORDER_ID, USER_ID, TRAIN_ID, ORDER_STATUS, PRICE, TICKET_TYPE, PASSENGER_ID) VALUES ('015', '2', '00001', 'paid', 5, 'adult', '2');