create table USERS
(
    USER_ID         VARCHAR2(255) not null
        primary key,
    USERNAME        VARCHAR2(255) not null,
    PASSWORD        VARCHAR2(255) not null,
    IS_STUDENT      NUMBER(1),
    STATUS          NUMBER(1),
    ID_NUMBER       VARCHAR2(255),
    PHONE_NUMBER    VARCHAR2(20),
    RIDING_INTERVAL VARCHAR2(255)
)
/

INSERT INTO SYSTEM.USERS (USER_ID, USERNAME, PASSWORD, IS_STUDENT, STATUS, ID_NUMBER, PHONE_NUMBER, RIDING_INTERVAL) VALUES ('111', 'ssj', '1', 1, 1, '002', '12345', '0');
INSERT INTO SYSTEM.USERS (USER_ID, USERNAME, PASSWORD, IS_STUDENT, STATUS, ID_NUMBER, PHONE_NUMBER, RIDING_INTERVAL) VALUES ('12345', 'zhc', '0', 1, 1, '001', '123456', '0');
INSERT INTO SYSTEM.USERS (USER_ID, USERNAME, PASSWORD, IS_STUDENT, STATUS, ID_NUMBER, PHONE_NUMBER, RIDING_INTERVAL) VALUES ('003', 'xjb', 'string', 1, 1, 'string', 'string', 'string');