create table FOOD
(
    FOOD_ID   VARCHAR2(255) not null
        primary key,
    FOOD_NAME VARCHAR2(255),
    PRICE     NUMBER
)
/

INSERT INTO SYSTEM.FOOD (FOOD_ID, FOOD_NAME, PRICE) VALUES ('001', '孜然烤肉饭', 32);
INSERT INTO SYSTEM.FOOD (FOOD_ID, FOOD_NAME, PRICE) VALUES ('002', '红烧排骨套餐', 42);
INSERT INTO SYSTEM.FOOD (FOOD_ID, FOOD_NAME, PRICE) VALUES ('003', '四喜丸子套餐', 40);
INSERT INTO SYSTEM.FOOD (FOOD_ID, FOOD_NAME, PRICE) VALUES ('004', '盐水鸭饭', 27);
INSERT INTO SYSTEM.FOOD (FOOD_ID, FOOD_NAME, PRICE) VALUES ('005', '鱼香肉丝饭', 30);
INSERT INTO SYSTEM.FOOD (FOOD_ID, FOOD_NAME, PRICE) VALUES ('006', '炒牛肉饭', 33);
INSERT INTO SYSTEM.FOOD (FOOD_ID, FOOD_NAME, PRICE) VALUES ('007', '宫保鸡丁套餐', 37);
INSERT INTO SYSTEM.FOOD (FOOD_ID, FOOD_NAME, PRICE) VALUES ('008', '梅菜烧肉', 45);
INSERT INTO SYSTEM.FOOD (FOOD_ID, FOOD_NAME, PRICE) VALUES ('009', '西蓝花炒肉', null);