create table STATION
(
    STATION_ID   VARCHAR2(20) not null
        primary key,
    STATION_NAME VARCHAR2(20)
)
/

INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('1', '北京');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('2', '北京东');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('3', '北京南');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('4', '北京西');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('5', '北京北');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('6', '上海');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('7', '上海西');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('8', '上海南');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('9', '广州');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('10', '广州东');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('11', '广州西');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('12', '鞍山');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('13', '安庆');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('14', '安亭北');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('15', '安亭西');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('16', '安阳');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('17', '安阳东');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('18', '保定东');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('19', '保定');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('20', '宝鸡');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('21', '百色');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('22', '重庆');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('23', '长沙');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('24', '长春');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('25', '成都');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('26', '福州');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('27', '贵阳');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('28', '呼和浩特');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('29', '哈尔滨');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('30', '合肥');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('31', '杭州');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('32', '杭州北');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('33', '海口');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('34', '济南');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('35', '昆明');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('36', '拉萨');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('37', '兰州');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('38', '南宁');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('39', '南京');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('40', '南昌');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('41', '沈阳');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('42', '石家庄');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('43', '太原');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('44', '乌鲁木齐');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('45', '武汉');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('46', '西宁');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('47', '西安');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('48', '银川');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('49', '郑州');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('50', '深圳');
INSERT INTO SYSTEM.STATION (STATION_ID, STATION_NAME) VALUES ('51', '厦门');